env: "local" # local, dev, prod
context_timeout: 5s
http:
  port: "5000"
  host: "localhost"
  read_timeout: 5s
  write_timeout: 5s
  shutdown_timeout: 5s
postgres: # может быть любая бд
  username: "postgres"
  password: "postgres"
  host: "45.12.236.183"
  port: "5432"
  database: "postgres"
# Ваши секреты
